package graph

import "errors"

// ErrChainBusy signals that an AppendEvent could not acquire the write lock
// within the busy timeout (SQLITE_BUSY). Capture treats it as a non-blocking
// skip rather than an error: the agent is never blocked on lock contention.
var ErrChainBusy = errors.New("event chain busy: append skipped")

// EventKind classifies what an Event records.
type EventKind string

const (
	EventKindTool      EventKind = "tool"
	EventKindOutcome   EventKind = "outcome"
	EventKindOutOfBand EventKind = "out-of-band"
)

// EventSource identifies the agent (or human) that produced an Event.
type EventSource string

const (
	EventSourceClaudeCode EventSource = "claude-code"
	EventSourceCursor     EventSource = "cursor"
	EventSourceHuman      EventSource = "human"
	EventSourceUnknown    EventSource = "unknown"
)

// EventRecord is the immutable, hash-chained source-of-truth record. Every other
// table (sessions, actions, event_files) is a Projection derived from the Event
// Log and can be regenerated by Replay.
type EventRecord struct {
	Seq            int64  // monotonic global ordering (assigned at append)
	EventID        string // ULID/UUID
	RecordedAt     int64  // unix seconds, capture wall-clock
	Source         EventSource
	InstanceID     string // = payload session_id; distinguishes concurrent agents
	Kind           EventKind
	HookEventName  string // "PostToolUse"
	ToolName       string
	Cwd            string
	TranscriptPath string
	PermissionMode string
	PayloadRaw     []byte // verbatim, post-redaction stdin bytes (hashed unit)
	PayloadSize    int64  // original size before truncation
	Truncated      bool
	// Outcome fields (zero unless Kind == EventKindOutcome)
	Command        string
	ExitCode       *int
	ExitCodeSource string // "reported" | "inferred"
	IsTest         bool
	IsBuild        bool
	TestName       string
	// Chain
	PrevHash string
	ThisHash string
}

// EventFile is one touched-file row derived for an Event on the cold path. It
// carries the File Blob Refs (git OIDs) for the before/after content so diffs can
// be reconstructed on demand without storing diff text. It is a Projection of the
// Event Log, regenerated by Rebuild.
type EventFile struct {
	EventSeq   int64
	FilePath   string
	BeforeBlob string
	AfterBlob  string
	ChangeKind string // "A" | "M" | "D" | "R"
	Additions  int
	Deletions  int
}

// FileChangeRow is one event_files row joined to its events row, the read unit
// behind the Provenance View and the diagnose Candidate blob refs. It carries the
// chain position, attribution, and File Blob Refs for one touched-file change.
type FileChangeRow struct {
	Seq          int64
	EventID      string
	RecordedAt   int64
	Source       string
	ToolName     string
	FilePath     string
	BeforeBlob   string
	AfterBlob    string
	ChangeKind   string
	LinkedCommit string // from action_produces for the path, empty if none
}

// EventHasher canonicalizes-and-hashes an EventRecord. Hashing (SHA-256) is an
// infrastructure concern, so the domain depends on this port, exactly as it
// already does with SessionIDGenerator.
type EventHasher interface {
	Hash(prevHash string, e EventRecord) string
}

// EventCursor iterates Events in seq order. Callers must Close it when done.
type EventCursor interface {
	Next() bool
	Event() EventRecord
	Err() error
	Close() error
}

// ChainBreakKind classifies the first integrity violation found by VerifyChain.
type ChainBreakKind string

const (
	ChainBreakRowEdited    ChainBreakKind = "ROW_EDITED"
	ChainBreakRowDeleted   ChainBreakKind = "ROW_DELETED"
	ChainBreakRowInserted  ChainBreakKind = "ROW_INSERTED"
	ChainBreakRowReordered ChainBreakKind = "ROW_REORDERED"
)

// ChainBreak describes the first integrity violation in the Event Log.
type ChainBreak struct {
	Seq              int64
	EventID          string
	Kind             ChainBreakKind
	ExpectedThisHash string
	StoredThisHash   string
}

// VerifyResult is the outcome of walking and recomputing the Event chain.
type VerifyResult struct {
	Status         string // "ok" | "broken"
	EventsTotal    int64
	EventsVerified int64
	FirstBreak     *ChainBreak
}

// GenesisHash is the prev_hash of the first Event (seq 1): 64 hex zeros.
const GenesisHash = "0000000000000000000000000000000000000000000000000000000000000000"
